### ISSUE TITLE
Form Builder Monitoring and Alerting

### ISSUE THREAD

**Issue by kcbotsh** [ministryofjustice/cloud-platform-user-guide#107]
CP team member to pair with @asmega for half a day. Provide guidance on best practice and help set up the required alerts from the team

**Comment by razvan-moj** [comment]
Done the session, covered a lot of topics at great speed including
 - Alertmanager and the use of PrometheusRules
 - Prometheus and ServiceMonitor
 - Grafana and ConfigMaps
 - ingress logs and Kibana
 - app instrumentation using https://prometheus.io/docs/instrumenting/clientlibs
 - basic debugging with `kubectl`
 - high-level view with https://kube-ops.cloud-platform.service.justice.gov.uk
