### ISSUE TITLE
Add a section on logging

### ISSUE THREAD

**Issue by digitalronin** [ministryofjustice/cloud-platform-user-guide#12]
Explain to users how their application logs are collected, how long
they are stored, and how to access them.

**Comment by AntonyBishop** [comment]
@digitalronin we do have a section on this. I searched "Logging" and got zero results but found content based on "Log" and "Logs". It is a small section but does cover the basics - https://user-guide.cloud-platform.service.justice.gov.uk/other-topics.html#how-to-access-my-log-data-using-kibana. Close or do you think there is more to this section?
