### ISSUE TITLE
Re: 'Upgrading your RDS database'

### ISSUE THREAD

**Issue by psoleckimoj** [ministryofjustice/cloud-platform-user-guide#1255]
Problem with 'Upgrading your RDS database' (https://user-guide.cloud-platform.service.justice.gov.uk/documentation/other-topics/upgrade-rds-db.html)

I'd suggest using `db.m5.*` rather than `m4` as it supports later versions of Postgres?

**Comment by sj-williams** [comment]
Added `db.m4` to previous generation instances upgrade advisory & AWS CLI command for checking database engine version availability for given db instance classes.
