### ISSUE TITLE
Re: 'Upgrading your RDS database'

### ISSUE THREAD

**Issue by psoleckimoj** [ministryofjustice/cloud-platform-user-guide#1263]
Problem with 'Upgrading your RDS database' (https://user-guide.cloud-platform.service.justice.gov.uk/documentation/other-topics/upgrade-rds-db.html)

Would be useful to mention `allow_major_version_upgrade = "true"` might need setting, that `rds_family` isn't a specific version number (i.e. it's 12 rather than 12.8) and that `db_engine_version` is specific (i.e. 12.8). Or a link to https://github.com/ministryofjustice/cloud-platform-terraform-rds-instance?ref=5.16.12%22 for options.

**Comment by sj-williams** [comment]
Completed, see:
https://app.zenhub.com/workspaces/cloud-platform-team-5ccb0b8a81f66118c983c189/issues/ministryofjustice/cloud-platform-user-guide/1295
