### ISSUE TITLE
Dead link in 'Creating your own custom alerts'

### ISSUE THREAD

**Issue by patrick-laa** [ministryofjustice/cloud-platform-user-guide#1477]
In 'Creating your own custom alerts' (https://user-guide.cloud-platform.service.justice.gov.uk/documentation/monitoring-an-app/how-to-create-alarms.html), and specifically in the [PrometheusRule examples section](https://user-guide.cloud-platform.service.justice.gov.uk/documentation/monitoring-an-app/how-to-create-alarms.html#prometheusrule-examples), there is a link out to https://github.com/ministryofjustice/cloud-platform-infrastructure/blob/main/terraform/aws-accounts/cloud-platform-aws/vpc/kops/components/resources/prometheusrule-examples/application-alerts.yaml which 404s.

**Comment by AntonyBishop** [comment]
Link has now been replaced. Thank you for your feedback.
