### ISSUE TITLE
Re: 'Creating your own custom alerts'

### ISSUE THREAD

**Issue by jhackett-ap** [ministryofjustice/cloud-platform-user-guide#1484]
Problem with 'Creating your own custom alerts' (https://user-guide.cloud-platform.service.justice.gov.uk/documentation/monitoring-an-app/how-to-create-alarms.html)

Hey folks, this page links to `https://github.com/ministryofjustice/cloud-platform-infrastructure/blob/main/terraform/aws-accounts/cloud-platform-aws/vpc/kops/components/resources/prometheusrule-examples/application-alerts.yaml` which appears to not exist now. Just a heads up! :)

**Comment by AntonyBishop** [comment]
Fixed
