### ISSUE TITLE
Re: 'ModSecurity - Web Application Firewall'

### ISSUE THREAD

**Issue by patrick-laa** [ministryofjustice/cloud-platform-user-guide#1495]
Problem with 'ModSecurity - Web Application Firewall' (https://user-guide.cloud-platform.service.justice.gov.uk/documentation/networking/modsecurity.html)

The example of a search with a unique ID, when modified to use a real ID, doesn't return any results. In fact "log_processed.transaction.producer.modsecurity=ModSecurity*", which is the filter the search applies, returns NO results of any kind, even without a unique ID specified.

So I think this link: https://kibana.cloud-platform.service.justice.gov.uk/_plugin/kibana/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:now-60m,to:now))&_a=(columns:!(_source),filters:!(('$state':(store:appState),meta:(alias:!n,disabled:!f,index:'8a728bc0-00eb-11ec-9062-27aa363b66a2',key:log_processed.transaction.producer.modsecurity,negate:!f,params:(query:'ModSecurity*'),type:phrase),query:(match_phrase:(log_processed.transaction.producer.modsecurity:'ModSecurity*')))),index:'8a728bc0-00eb-11ec-9062-27aa363b66a2',interval:auto,query:(language:kuery,query:%221663243008%22),sort:!(!('@timestamp',desc)))

... is broken.

**Comment by jaskaransarkaria** [comment]
This isn't really a bug we just updated how we handle modsec and haven't updated the readme. This section of the user guide needs updating https://user-guide.cloud-platform.service.justice.gov.uk/documentation/networking/modsecurity.html#logging
