### ISSUE TITLE
Re: 'Creating a file or object store'

### ISSUE THREAD

**Issue by rj-adams** [ministryofjustice/cloud-platform-user-guide#1534]
Problem with 'Creating a file or object store' (https://user-guide.cloud-platform.service.justice.gov.uk/documentation/deploying-an-app/object-store/create.html)

Examples link broken - [example guidance](https://github.com/ministryofjustice/cloud-platform-terraform-s3-bucket/tree/main/example)

**Comment by jakemulley** [comment]
Thanks @rj-adams, closing as resolved in #1528.
