### ISSUE TITLE
Re: 'Getting application metrics into Prometheus'

### ISSUE THREAD

**Issue by jsugarman** [ministryofjustice/cloud-platform-user-guide#173]
Problem with 'Getting application metrics into Prometheus' (https://user-guide.cloud-platform.service.justice.gov.uk/documentation/monitoring-an-app/application-metrics.html)

broken link   - repeated protocol
```
https://https//prometheus.cloud-platform.service.justice.gov.uk/
```

**Comment by vijay-veeranki-moj** [comment]
Thanks @jsugarman , fixed the link in this PR

https://github.com/ministryofjustice/cloud-platform-user-guide/pull/178
