### ISSUE TITLE
Broken "tasks" links

### ISSUE THREAD

**Issue by sldblog** [ministryofjustice/cloud-platform-user-guide#176]
I had to update links in our wiki pages as we were linking to [tasks.html#installation](https://user-guide.cloud-platform.service.justice.gov.uk/tasks.html#installation) which seems to have been moved to [documentation/getting-started/kubectl-config.html](https://user-guide.cloud-platform.service.justice.gov.uk/documentation/getting-started/kubectl-config.html#how-to-use-kubectl-to-connect-to-the-cluster).

In the past, I forgot to update cross-references, so I got curious and did a search in the site's code.

Unfortunately, it seems there are still a few links that reference to `tasks.html`: https://github.com/ministryofjustice/cloud-platform-user-guide/search?l=HTML%2BERB&q=tasks.html

**Comment by poornima-moj** [comment]
Updated the links referenced to html files which was removed as part of re-organising task.
