### ISSUE TITLE
Test "Namespace lost "recovery plan

### ISSUE THREAD

**Issue by kcbotsh** [ministryofjustice/cloud-platform-user-guide#197]
Test the plan set out in our draft disaster recovery doc.

If it works. Add the section to the DR  runbook using the templated format.

Add alarms and checks as needed

https://docs.google.com/document/d/1FABtEHcP_23ZAbMrwigXKYOkOHXXXmvtquPoWpGverU/edit#

**Comment by sablumiah** [comment]
Testing has been completed. This ticket will be closed when documentation has been created and added an entry into said document regarding this ticket
