### ISSUE TITLE
Test " Delete the whole cluster" recovery plan

### ISSUE THREAD

**Issue by kcbotsh** [ministryofjustice/cloud-platform-user-guide#208]
Test the plan set out in our draft disaster recovery doc.

If it works. Add the section to the DR runbook using the templated format.

Add alarms and checks as needed

https://docs.google.com/document/d/1FABtEHcP_23ZAbMrwigXKYOkOHXXXmvtquPoWpGverU/edit#

**Comment by poornima-moj** [comment]
build from code launching test cluster with starter pack

change something in the starter pack 
or deploy starter pack in different namespace

trigger velero backup job. 

destroy the cluster

rebuild the cluster from code

recover the namespaces from velero

check the changes are in place
