### ISSUE TITLE
Perform the htmlproofer check on new PRs

### ISSUE THREAD

**Issue by digitalronin** [ministryofjustice/cloud-platform-user-guide#397]
Currently, the htmlproofer check runs after the PR has been merged. It would be better if it ran on the PR *before* merging, when it's easier to see the results.

**Comment by AntonyBishop** [comment]
@digitalronin is this still required?

**Comment by digitalronin** [comment]
@AntonyBishop this is done
https://github.com/ministryofjustice/cloud-platform-user-guide/commit/0dade90850b35711593b4d10ae8aabe6a187d362
