### ISSUE TITLE
Pipeline for 'cloud-platform-account' terraform

### ISSUE THREAD

**Issue by davidread** [ministryofjustice/cloud-platform-user-guide#524]
Part of Epic: [Pipelines for terraform deployment](https://app.zenhub.com/workspaces/cloud-platform-team-5ccb0b8a81f66118c983c189/issues/ministryofjustice/cloud-platform/2446)

Pipeline for this repo: [terraform/cloud-platform-account](https://github.com/ministryofjustice/cloud-platform-infrastructure/tree/main/terraform/cloud-platform-account) - cloudtrail, velero, buckets, roles

Every git branch needs a ‘tf plan’. When merged it runs ‘tf apply’.

Deploying live1. (Deploying test clusters is separate to this ticket)

**Comment by AntonyBishop** [comment]
Done
