### ISSUE TITLE
Pipeline for 'global-resources' terraform

### ISSUE THREAD

**Issue by davidread** [ministryofjustice/cloud-platform-user-guide#525]
Part of Epic: [Pipelines for terraform deployment](https://app.zenhub.com/workspaces/cloud-platform-team-5ccb0b8a81f66118c983c189/issues/ministryofjustice/cloud-platform/2446)

Pipeline for this repo: [terraform/global-resources](https://github.com/ministryofjustice/cloud-platform-infrastructure/tree/main/terraform/global-resources) - AWS account, S3 buckets - kops state, Auth0 context?

Every git branch needs a ‘tf plan’. When merged it runs ‘tf apply’.

Deploying live1. (Deploying test clusters is separate to this ticket)

**Comment by AntonyBishop** [comment]
@pwyborn were you working on this story?

**Comment by davidread** [comment]
Ale says we need a bit of refactor - there are a number of things in the global terraform that are not actually global, like ES, Auth0 config.

**Comment by pwyborn** [comment]
For info - before the "firebreak sprint" removed the terraform  GuardDuty config in global-resources  as it was failing on redundant aws accounts (Also GuardDuty is now centrally managed).
Also corrected a problem where Vijay had merged an update - however it was not reflected in the state file.
