### ISSUE TITLE
Re: 'How to use `kubectl` to connect to the cluster'

### ISSUE THREAD

**Issue by MalcolmVonMoJ** [ministryofjustice/cloud-platform-user-guide#554]
Just reporting a difference betwixt the screenshot (`/images/github-authorize-moj.png`) in the document, and that which I actually found.  

I found this:
![image](https://user-images.githubusercontent.com/32877315/104320316-12cd9a00-54da-11eb-95d5-d35e3a98e87a.png)

**Comment by AntonyBishop** [comment]
Thanks @MalcolmVonMoJ. Have raised a PR #561 to update the image.

**Comment by AntonyBishop** [comment]
PR Merged
