### ISSUE TITLE
Use kops state terraform module within cloud-platform (code reducction & simplicity)

### ISSUE THREAD

**Issue by mogaal** [ministryofjustice/cloud-platform-user-guide#607]
All of this https://github.com/ministryofjustice/cloud-platform-infrastructure/blob/main/terraform/cloud-platform-account/main.tf#L114-L239 can be written as https://github.com/ministryofjustice/cloud-platform-terraform-kops-state-backend#usage . But it required some region replication tweaks.

**Comment by AntonyBishop** [comment]
Aged-out
