### ISSUE TITLE
Try kiosk, for managing k8s namespaces for tenants

### ISSUE THREAD

**Issue by davidread** [ministryofjustice/cloud-platform-user-guide#689]
https://github.com/loft-sh/kiosk

It's mentioned in the EKS multi-tenancy best practices: https://aws.github.io/aws-eks-best-practices/security/docs/multitenancy/ 

Maybe also look at https://devspace.cloud/ which is related

**Comment by sablumiah** [comment]
This was a successful spike to implement this, we would have to change our whole auth and how we manage users and their access. This is not something we want to do at the moment
