### ISSUE TITLE
Create a task doc explaining how to encrypt RDS connections

### ISSUE THREAD

**Issue by digitalronin** [ministryofjustice/cloud-platform-user-guide#69]
By default, applications' connections to RDS are not encrypted.

Create a walkthrough, with example code, that shows how to use encrypted connections to RDS.

See this guide from AWS:

https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/CHAP_PostgreSQL.html#PostgreSQL.Concepts.General.SSL

In particular, we should make the `rds.force_ssl` option available via the RDS module, and encourage teams to use it for their production RDS instances

**Comment by kcbotsh** [comment]
this is also request from Form builder team. Please let them know when this ticket is finished.

**Comment by mtrblmoj** [comment]
`rds.force_ssl` has been introduced with : https://github.com/ministryofjustice/cloud-platform/issues/950

Is this ticket still relevant ?

**Comment by alkar** [comment]
> `rds.force_ssl` has been introduced with : [ministryofjustice/cloud-platform#950](https://github.com/ministryofjustice/cloud-platform/issues/950)
> 
> Is this ticket still relevant ?

This is to document the required steps on the client side.

**Comment by digitalronin** [comment]
I think we should document how teams can connect to the RDS instance, if force_ssl is enabled.
