### ISSUE TITLE
Placeholder for updating runbooks section(s) for cluster component upgrades

### ISSUE THREAD

**Issue by leoncarrington** [ministryofjustice/cloud-platform-user-guide#753]
Following on from the retrospective held on 23rd July,  there were some discussion about the current state of our runbook and wether any improvements are needed to be made to https://runbooks.cloud-platform.service.justice.gov.uk/upgrade-cluster-components.html#upgrade-cluster-components to make the process more smoother.

More details to follow after backlog refinement & discussion...

**Comment by AntonyBishop** [comment]
Aged out
