### ISSUE TITLE
Re: 'Kubernetes Cronjobs'

### ISSUE THREAD

**Issue by exonian** [ministryofjustice/cloud-platform-user-guide#858]
Problem with 'Kubernetes Cronjobs' (https://user-guide.cloud-platform.service.justice.gov.uk/documentation/other-topics/Cronjobs.html)

Remove references to using `ttlSecondsAfterFinished` and probably provide alternative advice for the new way of doing limits

**Comment by AntonyBishop** [comment]
Updated
