### ISSUE TITLE
Update Tiller RBAC documentation

### ISSUE THREAD

**Issue by mtrblmoj** [ministryofjustice/cloud-platform-user-guide#90]
Update the documentation related to the Helm tiller so that it does not rely on a privileged ClusterRole. 
Ideally, and to be confirmed, it would use the _privileged_ PSP. 

https://user-guide.cloud-platform.service.justice.gov.uk/tasks.html#tiller-rbac-configuration

**Comment by vijay-veeranki-moj** [comment]
The ClusterRole is with in the namespace and not providing any cluster level privileges.

https://mojdt.slack.com/archives/C514ETYJX/p1527862306000630
