### ISSUE TITLE
Re: 'Continuous Deployment of an application using CircleCI and Helm'

### ISSUE THREAD

**Issue by jsugarman** [ministryofjustice/cloud-platform-user-guide#960]
Problem with 'Continuous Deployment of an application using CircleCI and Helm' (https://user-guide.cloud-platform.service.justice.gov.uk/documentation/deploying-an-app/using-circleci-for-continuous-deployment.html)

Building and pusshing to ECR example

`get-login` ([get-login](https://docs.aws.amazon.com/cli/latest/reference/ecr/get-login.html))is deprecated. example should probably be updated to use `get-login-password` instead.

```
aws ecr get-login-password --region ${AWS_DEFAULT_REGION} | docker login --username AWS --password-stdin ${ECR_ENDPOINT}
```

**Comment by vijay-veeranki** [comment]
PR:
https://github.com/ministryofjustice/cloud-platform-user-guide/pull/976/files
